In [2]:
import pandas as pd

In [9]:
conv = pd.read_excel('Table50.xls')
conv.set_index('Violations', inplace=True)
del conv.index.name
conv = conv.transpose()
conv.head()

,All violations,Immigration violations,Entry of aliens illegally,Reentry of deported aliens,"Bringing in, transporting, harboring illegal aliens",Fraud and false statements to obtain or confer immigration benefits,"Fraud, forgery, misuse of visas, alien registration, and other documents","Fraud, forgery, misuse of identification documents",Conspiring to defraud the United States,"Employing unauthorized aliens, peonage, false attestations for employment",...,Other naturalization violations,Total other violations,Racketeering,"Terrorism, threat to national security",Money laundering and financial fraud,"Weapons trafficking, unlawful possession by aliens",Drug trafficking,Obstructing justice,Alien prostitution,Other other violations
1992,9865,9766,6341,477,977,39,306,497,109,39,...,0,0,0,0,0,0,498,0,0,401
1993,11685,10189,7187,767,1008,72,383,688,37,40,...,0,1209,692,0,20,46,358,68,0,25
1994,10210,9180,6610,803,731,28,353,638,6,11,...,0,870,467,0,11,44,292,42,NaN,13
1995,12075,11110,7446,1475,758,39,301,1032,6,52,...,0,852,443,0,15,32,272,46,5,39
1996,12121,11014,6361,2331,1295,28,254,681,12,48,...,0,974,662,0,3,16,222,29,13,29

In [11]:
conv.to_csv('../../Data/conviction.csv')