In [1]:
import pandas as pd

In [17]:
acc = pd.read_excel('accomplishmentsINS92-01.xls')
acc.set_index('Accomplishment', inplace=True)
del acc.index.name
acc = acc.transpose()
# acc.to_csv('../../Data/accomplishments.csv')

In [18]:
acc.head()

,Criminal Cases,Criminal Prosecutions,Criminal Convictions,Employer Cases,Employer Warnings,Employer Notice of Intent to Fine,Employer Final orders,Employer Arrests,Fraud Cases,Fraud Prosecutions,Fraud Convictions,Smuggling Cases,Smugglers arrested,Smuggled aliens arrested,Smuggling Prosecutions,Smuggling Convictions,Inspection Cases,Inspection Arrests
1992,38716,2027,1688,7053,840,1461,1063,8027,3428,532,494,7073,13454,38498,3030,NaN,24048,6507
1993,45291,2041,1954,6237,758,1302,944,7630,4416,525,421,6955,11244,48017,2491,NaN,23841,7375
1994,46236,2386,2172,6169,683,1063,836,7554,5800,308,225,4750,8787,53078,2029,NaN,19364,8458
1995,45619,1965,1590,5283,550,1055,909,10014,6455,389,257,5358,8580,68203,2636,NaN,23624,8793
1996,54065,1468,1254,5149,668,1019,808,14164,4369,613,339,2643,4699,43243,3360,2838,33138,15365